version: '3.8'
services:
  web:
    image: php:8.0-apache
    container_name: project_finder_web
    ports:
      - "8080:80"
    volumes:
      - /Users/katy/Documents/GitHub/Project-Finder:/var/www/html # Mount the correct directory containing your PHP files
    depends_on:
      - injection.php
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: project_finder_db
    ports:
      - "8889:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rooty
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"  # Not needed if you set a root password
      MYSQL_DATABASE: Project-Finder
    volumes:
      - ./sql:/docker-entrypoint-initdb.d # Keep this for database initialization scripts
      - mysql_data:/var/lib/mysql # Define the named volume here

volumes:
  mysql_data: # Define the named volume here