services:
  web:
    image: php:8.0-apache
    container_name: project_finder_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: project_finder_db
    restart: always
    ports:
      - "8889:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rooty
      MYSQL_DATABASE: Project-Finder
      # Debug options:
      MYSQL_LOG_CONSOLE: "true"
    volumes:
      # Start with just the data volume, add others after we confirm it works
      - mysql_data:/var/lib/mysql


    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: