docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/STUDENT.csv project_finder_db:/var/lib/mysql-files
docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/ASSOCIATED_WITH.csv project_finder_db:/var/lib/mysql-files
docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/INFRACTION.csv project_finder_db:/var/lib/mysql-files
docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/PROJECT_CODING_LANGUAGES.csv project_finder_db:/var/lib/mysql-files
docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/PROJECT.csv project_finder_db:/var/lib/mysql-files
docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/STUDENT_SOCIALS.csv project_finder_db:/var/lib/mysql-files
docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/WORKS_ON.csv project_finder_db:/var/lib/mysql-files
docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/1Create.sql project_finder_db:/var/lib/mysql-files
docker cp /Users/katy/Documents/GitHub/Project-Finder/sql/2Load.sql project_finder_db:/var/lib/mysql-files
