docker cp ./sql/STUDENT.csv project_finder_db:/var/lib/mysql-files
docker cp ./sql/ASSOCIATED_WITH.csv project_finder_db:/var/lib/mysql-files
docker cp ./sql/INFRACTION.csv project_finder_db:/var/lib/mysql-files
docker cp ./sql/PROJECT_CODING_LANGUAGES.csv project_finder_db:/var/lib/mysql-files
docker cp ./sql/PROJECT.csv project_finder_db:/var/lib/mysql-files
docker cp ./sql/STUDENT_SOCIALS.csv project_finder_db:/var/lib/mysql-files
docker cp ./sql/WORKS_ON.csv project_finder_db:/var/lib/mysql-files
docker cp ./sql/1Create.sql project_finder_db:/var/lib/mysql-files
docker cp ./sql/2Load.sql project_finder_db:/var/lib/mysql-files
