-- Create the table & name from CSV file
CREATE TABLE STUDENT (
  -- Enter each entity, data type, characters, and any additional restrictions
    NetID CHAR(9) PRIMARY KEY,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(15),
    Name VARCHAR(255) NOT NULL,
    Pronouns VARCHAR(50)
);

CREATE TABLE STUDENT_SOCIALS (
    NetID CHAR(9),
    Platform VARCHAR(100) NOT NULL,
    Username VARCHAR(100) NOT NULL,
    PRIMARY KEY (NetID, Platform),
    FOREIGN KEY (NetID) REFERENCES STUDENT(NetID) ON DELETE CASCADE
);

CREATE TABLE PROJECT (
    PID INT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description VARCHAR(500),
    Tag VARCHAR(255) NOT NULL,
    Capacity INT DEFAULT 3,
    Date_posted TIMESTAMP NOT NULL,
    NetID CHAR(9) NOT NULL,
    FOREIGN KEY (NetID) REFERENCES STUDENT(NetID) ON DELETE RESTRICT
);

CREATE TABLE PROJECT_CODING_LANGUAGES (
    PID INT,
    Language VARCHAR(100) NOT NULL,
    Relative_experience VARCHAR(50),
    PRIMARY KEY (PID, Language),
    FOREIGN KEY (PID) REFERENCES PROJECT(PID) ON DELETE CASCADE
);

CREATE TABLE WORKS_ON (
    NetID CHAR(9),
    PID INT,
    PRIMARY KEY (NetID, PID),
    FOREIGN KEY (NetID) REFERENCES STUDENT(NetID) ON DELETE CASCADE,
    FOREIGN KEY (PID) REFERENCES PROJECT(PID) ON DELETE CASCADE
);

CREATE TABLE INFRACTION (
    InfractionID INT PRIMARY KEY,
    Description VARCHAR(500) NOT NULL
);

CREATE TABLE ASSOCIATED_WITH (
    InfractionID INT,
    NetID CHAR(9),
    Resolved INT DEFAULT 0,
    PRIMARY KEY (InfractionID, NetID),
    FOREIGN KEY (InfractionID) REFERENCES INFRACTION(InfractionID) ON DELETE CASCADE,
    FOREIGN KEY (NetID) REFERENCES STUDENT(NetID) ON DELETE CASCADE
);
