-- Load STUDENT data
LOAD DATA INFILE '/var/lib/mysql-files/STUDENT.csv'
-- Specify the table name
INTO TABLE STUDENT
-- each entity (pwd, netID, etc) separated by a ',' w/no spaces
FIELDS TERMINATED BY ','
-- Each field enclosed by quotes- these are delimiters not data 
ENCLOSED BY '"'
-- One entry per line
LINES TERMINATED BY '\n'
-- Skip Headers
IGNORE 1 ROWS;

-- Load STUDENT_SOCIALS data
-- Same/Similar structure for all data 
LOAD DATA INFILE '/var/lib/mysql-files/STUDENT_SOCIALS.csv'
INTO TABLE STUDENT_SOCIALS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load PROJECT data
LOAD DATA INFILE '/var/lib/mysql-files/PROJECT.csv'
INTO TABLE PROJECT
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load PROJECT_CODING_LANGUAGES data
LOAD DATA INFILE '/var/lib/mysql-files/PROJECT_CODING_LANGUAGES.csv'
INTO TABLE PROJECT_CODING_LANGUAGES
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load WORKS_ON data
LOAD DATA INFILE '/var/lib/mysql-files/WORKS_ON.csv'
INTO TABLE WORKS_ON
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load INFRACTION data
LOAD DATA INFILE '/var/lib/mysql-files/INFRACTION.csv'
INTO TABLE INFRACTION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

-- Load ASSOCIATED_WITH data
LOAD DATA INFILE '/var/lib/mysql-files/ASSOCIATED_WITH.csv'
INTO TABLE ASSOCIATED_WITH
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
